/* Addresses should be listed in order */
_icon_item_staticSegmentRomStart = 0x007bd000;
_item_name_staticSegmentRomStart = 0x00880000;
z64_EquippedItemOutlineTex = 0x2000E00;
DmaMgr_RequestAsync = 0x80000d28;
DmaMgr_RequestSync = 0x80000df0;
Flags_GetSwitch = 0x8002049C;
Flags_SetSwitch = 0x800204D0;
Flags_UnsetSwitch = 0x80020510;
Flags_GetUnknown = 0x80020554;
Flags_SetUnknown = 0x80020588;
Flags_UnsetUnknown = 0x800205C8;
Flags_GetTreasure = 0x8002060C;
Flags_SetTreasure = 0x80020624;
Flags_GetClear = 0x80020640;
Flags_SetClear = 0x80020658;
Flags_UnsetClear = 0x80020674;
Flags_GetTempClear = 0x80020694;
Flags_SetTempClear = 0x800206AC;
Flags_UnsetTempClear = 0x800206C8;
Flags_GetCollectible = 0x800206E8;
Flags_SetCollectible = 0x8002071C;
Actor_GetScreenPos = 0x80022b14;
Actor_SpawnEntry = 0x800255c4;
Actor_SetColorFilter = 0x80027090;
Actor_Kill = 0x80020eb4;
Npc_TrackPoint = 0x80027854;
BgCheck_AnyLineTest1 = 0x80030ae8;
QuestHint_GetNaviTextId = 0x8005977c;
CutsceneFlags_Get = 0x8005991C;
Lights_PointGlowSetInfo = 0x80065c30;
Math_Vec3f_Yaw = 0x80063f00;
Magic_Reset = 0x80072548;
Math_SmoothStepToS = 0x80064508;
Player_HoldsHookshot = 0x80079bd4;
Player_GetExplosiveHeld = 0x80079d74;
z64_Gfx_SetupDL_42Opa = 0x8007E868;
SkinMatrix_Vec3fMtxFMultXYZW = 0x8008ec20;
Matrix_Push = 0x800aa6ec;
Matrix_Pop = 0x800aa724;
Matrix_Scale = 0x800aa8fc;
Matrix_SetTranslateRotateYXZ = 0x800ab510;
Matrix_MultVec3f = 0x800ab958;
func_800982FC = 0x80081740;
Audio_StopCurrentMusic = 0x800C7684;
sprintf = 0x800CE7b4;
Message_OpenText = 0x800DC838;
Fault_AddHungupAndCrashImpl = 0x800AF564;
z64_ItemIcons = 0x800F8D2C;
gObjectTable = 0x800f8ff8;
gKaleidoMgrCurOvl = 0x800fe4bc;
z64_SfxDefaultPos = 0x80104394;
z64_SfxDefaultFreqAndVolScale = 0x801043A0;
z64_SfxDefaultReverb = 0x801043A8;
gMapData = 0x8011bf10;
R_EXITED_SCENE_RIDING_HORSE = 0x801c7cf0;
KaleidoScope_DrawAmmoCount = 0x8038EA10;
KaleidoScope_SetCursorVtx = 0x8038EF94;
KaleidoScope_QuadTextureIA8 = 0x80394200;
KaleidoScope_MoveCursorToSpecialPos = 0x80394524;
KaleidoScope_DrawQuadTextureRGBA32 = 0x80394588;
KaleidoScope_DrawCursor = 0x80394B00;
z64_AmmoItems = 0x8039EAA0;
z64_SlotAgeReqs = 0x8039F114;
z64_sEquipState = 0x8039EAB0;
z64_sEquipAnimTimer = 0x8039EAB4;
z64_sEquipMoveTimer = 0x8039EAB8;
gActorOverlayTable = 0x800E8530;
Message_CloseTextbox = 0x800d6218;
sSetupDL = 0x800f7d50;
Player_UseItem = 0x8038c9a0; /* 0x80834000 */
OVL_EnOkarinaTag_Action2 = 0x80a872d0;
OVL_EnOkarinaTag_Action1 = 0x80a87088;


/* Dump of debug stuff addresses */
Flags_UnsetClear = 0x80020674;
gActorOverlayTable = 0x800e8530;
gObjectTable = 0x800f8ff8;

Player_SetupIdleFromGetItem = 0x803a4a10;
Player_ObjectDMARequest = 0x8039190c;
sGraphStackInfo = 0x80120b98;
StackCheck_Check = 0x8000198c;
lldiv = 0x800d4e30;
memcpy = 0x800d2350;
ZeldaArena_Free = 0x80066c90;
Object_IsLoaded = 0x80081688;
Play_ClearCamera = 0x8009d21c;
Player_UseItem = 0x8038C9A0;
OnePointCutscene_Attention = 0x8006ba10;
Fault_LogThreadContext = 0x800ae338;

Player_SetupGetItem = 0x80390EF8;
Player_DetachHeldActor = 0x80388D20;
Player_ObjectDMARequest = 0x8039190C;
Player_AnimPlayOnceAdjusted = 0x80388C34;
Player_ZeroXZNormalCamera = 0x80388B78;
Object_GetSlot = 0x80081628;
gEntranceTable = 0x800f9c90;
Actor_FindNearby = 0x80028158;
Math_AsymStepToF = 0x80063acc;
DynaPoly_GetActor = 0x80031464;
Player_SetTurnAroundCamera = 0x8038C8F4;
TitleCard_Clear = 0x80020e80;
func_80837B18 = 0x8038e5b4;

sEntranceIconMapIndex = 0x800f553c;
DmaMgr_RequestSync = 0x80000df0;
Map_Init = 0x8006c340;
gMapData = 0x8011bf10;
_map_grand_staticSegmentRomStart = 0x00967000;
DmaMgr_RequestAsync = 0x80000d28;
gMapDataTable = 0x800f72d8;
Actor_SpawnEntry = 0x800255C4;
Actor_SetObjectDependency = 0x80020fa4;
Interface_ChangeHudVisibilityMode = 0x8006d8e0;

SkinMatrix_Vec3fMtxFMultXYZW = 0x8008ec20;
Matrix_SetTranslateRotateYXZ = 0x800ab510;
Matrix_Scale = 0x800aa8fc;
Matrix_MultVec3f = 0x800ab958;
gIdentityMtx = 0x800fedb0;
Math_Vec3s_ToVec3f = 0x80063ccc;
Math3D_DefPlane = 0x800a67dc;
Graph_Alloc = 0x800a1a2c;
Lights_PointGlowSetInfo = 0x80065c30;

Math_Vec3f_Yaw = 0x80063f00;

Magic_RequestChange = 0x80072588;
Magic_Fill = 0x80072500;

Actor_GetScreenPos = 0x80022b14;
Effect_GetByIndex = 0x8001a890;
Math_SinS = 0x800636c4;
Math_CosS = 0x80063684;
EffectSsKiraKira_SpawnSmall = 0x8001c66c;

gKaleidoMgrOverlayTable = 0x800fe480;
sKaleidoAreaPtr = 0x800fe4b8;
gKaleidoMgrCurOvl = 0x800fe4bc;

Play_ClearCamera = 0x8009d21c;

Player_ActionHandler_13 = 0x808390fc;